# Generated by Django 2.2.2 on 2019-06-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190608_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1),
        ),
    ]
