# Generated by Django 2.2.2 on 2019-06-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_banlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
