# Generated by Django 2.2.2 on 2019-06-08 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пакета')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('img', models.ImageField(upload_to='courses/professions/', verbose_name='Изображение профессии')),
            ],
            options={
                'verbose_name': 'Пакет курсов',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='courses/', verbose_name='Изображение курса')),
                ('company_id', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
                'verbose_name': 'Курс',
            },
        ),
    ]
