# Generated by Django 2.2.2 on 2019-06-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesInPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Package')),
            ],
            options={
                'verbose_name': 'Курс в пакете',
                'verbose_name_plural': 'Курсы в пакете',
            },
        ),
    ]
