# Generated by Django 2.2.2 on 2019-06-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursesinpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(null=True, upload_to='courses/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(null=True, upload_to='courses/professions/', verbose_name='Изображение профессии'),
        ),
    ]
