# Generated by Django 2.2.2 on 2019-06-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190608_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesForLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='lesson/', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название урока')),
                ('video', models.URLField(verbose_name='Видеоурок')),
                ('text', models.TextField(verbose_name='Текст урока')),
            ],
            options={
                'verbose_name_plural': 'Уроки',
                'verbose_name': 'Урок',
            },
        ),
        migrations.CreateModel(
            name='LessonToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Lesson')),
            ],
            options={
                'verbose_name': 'Урок к курсу',
            },
        ),
        migrations.CreateModel(
            name='FilesToLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.FilesForLesson')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Lesson')),
            ],
            options={
                'verbose_name': 'Файл для урока',
            },
        ),
    ]
