# Generated by Django 2.2.2 on 2019-06-08 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_filesforlesson_filestolesson_lesson_lessontocourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='filestolesson',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.FilesForLesson'),
        ),
        migrations.AlterField(
            model_name='filestolesson',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видеоурок'),
        ),
        migrations.AlterField(
            model_name='lessontocourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lessontocourse',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Lesson'),
        ),
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='courses/professions/', verbose_name='Изображение профессии'),
        ),
    ]
