# Generated by Django 2.2.2 on 2019-06-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='main/', verbose_name='Логотип')),
                ('meta_keywords', models.TextField(verbose_name='Ключевые слова')),
                ('description', models.TextField(verbose_name='Описание (поисковик)')),
            ],
            options={
                'verbose_name': 'Основные настройки сайта',
            },
        ),
    ]
