# Generated by Django 2.2.2 on 2019-06-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_usersincompanies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Картинка компании'),
        ),
        migrations.AlterField(
            model_name='usersincompanies',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'moderator'), (3, 'member')], default='3'),
        ),
    ]
